# Generated by Django 5.2.8 on 2025-11-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='NomChefEtablissement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom du Chef d'Établissement"),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='TelephoneEtablissement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Téléphone de l'Établissement"),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='adresseEtablissement',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Adresse de l'Établissement"),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='anneeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.annee_scolaire', verbose_name='Année ID'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='identification_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.identifications', verbose_name='identification_id'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='informations_generale_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.informations_generale', verbose_name='Informations_generale ID'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='localisation_administrative_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.localisation_administrative', verbose_name='Localisation_administrative ID'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='localisation_scolaire_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.localisation_scolaire', verbose_name='Localisation_scolaire ID'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='nom_norm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom Normalisé'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='provedId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proveds', verbose_name='Proveds ID'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='provinceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provinces', verbose_name='Provinces ID'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='reference_juridique_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reference_juridique', verbose_name='reference_juridique ID'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='sousProvedId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sous_proved', verbose_name='Sous_proved ID'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='territoireId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.territoires', verbose_name='Territoires ID'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='type_enseignement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Type d'Enseignement"),
        ),
    ]
